### ISSUE TITLE
can't build image on OSX Mojave

### ISSUE THREAD

**Issue by paxinos** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#1]
svn cache (/opt/conda/conda-bld/svn_cache)
Size:                                           0 B

Total:                                          0 B
Removing /opt/conda/conda-bld/src_cache
Removing /opt/conda/conda-bld/git_cache
Removing /opt/conda/conda-bld/hg_cache
Removing /opt/conda/conda-bld/svn_cache
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Node v8.10.0
No other errors were seen in the log.

> /opt/conda/bin/npm pack '@jupyter-widgets/jupyterlab-manager@^0.35'
jupyter-widgets-jupyterlab-manager-0.35.0.tgz

Errored, use --debug for full output:
ValueError: 
"@jupyter-widgets/jupyterlab-manager@0.35.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=2.2.1 <3.0.0          >=1.1.0 <2.0.0   @jupyterlab/coreutils
>=0.19.2 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime
>=3.2.1 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services
The command '/bin/sh -c conda install --quiet --yes     'blas=*=openblas'     'ipywidgets=7.2*'     'pandas=0.22*'     'flask=0.12.2'     'numexpr=2.6*'     'matplotlib=2.1*'     'scipy=1.0*'     'seaborn=0.8*'     'scikit-learn=0.19*'     'scikit-image=0.13*'     'sympy=1.1*'     'cython=0.28*'     'patsy=0.5*'     'statsmodels=0.8*'     'cloudpickle=0.5*'     'dill=0.2*'     'numba=0.38*'     'bokeh=0.12*'     'sqlalchemy=1.2*'     'hdf5=1.10*'     'h5py=2.7*'     'vincent=0.4.*'     'beautifulsoup4=4.6.*'     'jpype1'     'protobuf=3.*'     'xlrd'  &&     conda remove --quiet --yes --force qt pyqt &&     conda clean -tipsy &&     jupyter nbextension enable --py widgetsnbextension --sys-prefix &&     jupyter labextension install @jupyter-widgets/jupyterlab-manager@^0.35 &&     jupyter labextension install jupyterlab_bokeh@^0.5.0 &&     npm cache clean --force &&     rm -rf $CONDA_DIR/share/jupyter/lab/staging &&     rm -rf /home/$NB_USER/.cache/yarn &&     rm -rf /home/$NB_USER/.node-gyp &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1

**Comment by paxinos** [comment]
Same issue on Ubuntu 16.04.3

Total:                                          0 B
Removing /opt/conda/conda-bld/src_cache
Removing /opt/conda/conda-bld/git_cache
Removing /opt/conda/conda-bld/hg_cache
Removing /opt/conda/conda-bld/svn_cache
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Node v8.10.0

> /opt/conda/bin/npm pack '@jupyter-widgets/jupyterlab-manager@^0.35'
jupyter-widgets-jupyterlab-manager-0.35.0.tgz

Errored, use --debug for full output:
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.35.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=2.2.1 <3.0.0          >=1.1.0 <2.0.0   @jupyterlab/coreutils
>=0.19.2 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime
>=3.2.1 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services
ERROR: Service 'mtsw' failed to build: The command '/bin/sh -c conda install --quiet --yes     'blas=*=openblas'     'ipywidgets=7.2*'     'pandas=0.22*'     'flask=0.12.2'     'numexpr=2.6*'     'matplotlib=2.1*'     'scipy=1.0*'     'seaborn=0.8*'     'scikit-learn=0.19*'     'scikit-image=0.13*'     'sympy=1.1*'     'cython=0.28*'     'patsy=0.5*'     'statsmodels=0.8*'     'cloudpickle=0.5*'     'dill=0.2*'     'numba=0.38*'     'bokeh=0.12*'     'sqlalchemy=1.2*'     'hdf5=1.10*'     'h5py=2.7*'     'vincent=0.4.*'     'beautifulsoup4=4.6.*'     'jpype1'     'protobuf=3.*'     'xlrd'  &&     conda remove --quiet --yes --force qt pyqt &&     conda clean -tipsy &&     jupyter nbextension enable --py widgetsnbextension --sys-prefix &&     jupyter labextension install @jupyter-widgets/jupyterlab-manager@^0.35 &&     jupyter labextension install jupyterlab_bokeh@^0.5.0 &&     npm cache clean --force &&     rm -rf $CONDA_DIR/share/jupyter/lab/staging &&     rm -rf /home/$NB_USER/.cache/yarn &&     rm -rf /home/$NB_USER/.node-gyp &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1

**Comment by mervesarac** [comment]
Same issue on MacOS Mojave 10.14.2

**Comment by mikhailklassen** [comment]
Thanks for alerting me to this. I've updated the Dockerfile and fixed the dependencies that were causing this issue. The image should now build.

I've also made updates to the ReadMe file and pushed a compiled Docker image to Docker Hub, if people wish to just download a prebuilt image.

**Comment by mikhailklassen** [comment]
I'm going to close this issue for now, but don't hesitate to reopen it if the error persists.
