### ISSUE TITLE
404 : Not Found

### ISSUE THREAD

**Issue by uzabumuhire** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#12]
I am using Docker on Mac OS Mojave 10.14.13 and "Appendix C - Python & Jupyter Notebook Tips" section "Serving Static Content" can't compile and generate the following error:

404 : Not Found
You are requesting a page that does not exist!

**Comment by ptwobrussell** [comment]
@uzabumuhire - Thanks for pointing this out. It's unlikely that you'll need to use this example to complete any of the exercises in the book, and it's included for awareness. The reason it isn't working is that there isn't a `resources/appc-pythontips/hello.txt` file that's checked in. I'll go ahead and add that file now and then close this out.
