### ISSUE TITLE
Invalid Scopes: friends_likes

### ISSUE THREAD

**Issue by uzabumuhire** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#16]
I am using Docker to run Jupyter Notebook on Mac OS Mojave 10.14.13 and "**Appendix B - OAuth Primer**" section "**Example 2. Facebook OAuth 2.0 Flow**" have Facebook generating the following error after having resolved issue #15 :

> Invalid Scopes: friends_likes. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

To resolve the issue I change `EXTENDED_PERMS = ['user_likes', 'friends_likes']` to `EXTENDED_PERMS = ['user_likes'` by removing the friends_likes permission.

**Comment by mikhailklassen** [comment]
@uzabumuhire -- I've removed `friends_likes` permission. Facebook got rid of this privilege to improve the privacy of its platform.
