### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'resources/ch02-facebook/access_token.txt'

### ISSUE THREAD

**Issue by uzabumuhire** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#17]
I am using Docker to run Jupyter Notebook on Mac OS Mojave 10.14.13 and "**Appendix B - OAuth Primer**" section "**Example 2. Facebook OAuth 2.0 Flow**" can't compile and generate the following error after having resolved issue #16 :

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-12-e6b1d28997e2> in <module>
>      69 webserver.run(host='0.0.0.0')
>      70 
> ---> 71 access_token = open(OAUTH_FILE).read()
>      72 
>      73 print(access_token)
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'resources/ch02-facebook/access_token.txt'

This error is generating the following error on localhost:5000 

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by mikhailklassen** [comment]
@uzabumuhire -- Thanks for pointing this out. I've created an empty file, `access_token.txt` in a folder 'resources/ch02-facebook'. The access token will now be written to that file.

Remember that if you've forked this repo into your own GitHub account, consider adding `access_token.txt` to your `.gitignore` file. It would be easy for the access token data to be written to the empty file and then have those changes committed by accident.
