### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'resources/ch03-linkedin/linkedin.authorization_code'

### ISSUE THREAD

**Issue by uzabumuhire** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#18]
I am using Docker to run Jupyter Notebook on Mac OS Mojave 10.14.13 and "**Appendix B - OAuth Primer**" section "**Example 3. Using LinkedIn OAuth credentials to receive an access token an authorize an application**" can't compile and generate the following error :

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-13-3087637a0a58> in <module>
>      56 # seems to need full automation because the authorization code expires very quickly.
>      57 
> ---> 58 auth.authorization_code = open(OAUTH_FILE).read()
>      59 auth.get_access_token()
>      60 
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'resources/ch03-linkedin/linkedin.authorization_code'

This error is generating the following error on localhost:5000

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by mikhailklassen** [comment]
@uzabumuhire -- Thanks for catching this. It seems like perhaps LinkedIn has also reduced the permissions given to third-party apps. I've updated the requested permissions and updated the reference ch03-linkedin -> ch04-linkedin.

I've tested the code, and as long as your app settings on the LinkedIn Developer platform match the parameter settings in the Jupyter notebook (check the permissions and REDIRECT_URL), then it should work.

Closing this issue for now.
