### ISSUE TITLE
Unable to get the docker file working.

### ISSUE THREAD

**Issue by Kyrke** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#20]
I've tried both options provided to install the docker, but neither works for me. In each instance I get an error message:

**Option 1 fails right away with this:**
Error response from daemon: Get https://registry-1.docker.io/v2/mikhailklassen/mining-the-social-web-3rd-edition/manifests/latest: unauthorized: incorrect username or password

**Building the docker myself, this is how far I get:**
Sending build context to Docker daemon  85.71MB
Step 1/25 : FROM jupyter/minimal-notebook
Get https://registry-1.docker.io/v2/jupyter/minimal-notebook/manifests/latest: unauthorized: incorrect username or password

I have the following Docker version: Docker version 18.09.2, build 6247962

Please help! I'm so excited to get into this book and am stuck at step 0

**Comment by kazuhirow** [comment]
Could you check using email address for docker desktop? If you use email address, docker could not work correctly. I tried change email to user name for docker desktop, docker works well.

**Comment by Kyrke** [comment]
That worked. Thank you! I really appreciate the help. I never would have figured that out on my own.
