### ISSUE TITLE
Binder error

### ISSUE THREAD

**Issue by filmenczer** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#31]
The quickstart Binder link https://mybinder.org/v2/gh/mikhailklassen/Mining-the-Social-Web-3rd-Edition/binder?filepath=notebooks%2F results in an error on the Binder website: `Could not resolve ref for gh:mikhailklassen/Mining-the-Social-Web-3rd-Edition/binder. Double check your URL.`

**Comment by mikhailklassen** [comment]
Thanks for bringing this to my attention. The Binder link was pointing to the wrong branch. I had been testing the repository on a specific feature branch, but when I merged all those changes back into master, I forgot to update the link. An embarrassing mistake, but also quick to fix. My sincere apologies. The issue has now been resolved.
