### ISSUE TITLE
docker-compose.yml not found

### ISSUE THREAD

**Issue by BerthaBrenes** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#34]

**Comment by BerthaBrenes** [comment]
Couldnt find docker-compose.yml in the repo

**Comment by labirintoffhs** [comment]
Could not finde the docker-compose.yml file either

**Comment by mikhailklassen** [comment]
Hi there! I've been making some updates to the code and now you no longer need docker-compose for it to run. Do I still have references to docker-compose.yml somewhere?

**Comment by BerthaBrenes** [comment]
I read the references from the book.
But I'm using the repo2docker with this url of GitHub and everything is working so i will close this issue if docker-compose.yml is not longer useful.
