### ISSUE TITLE
Unable to use token to sign into Jupyter I get Invalid credentials

### ISSUE THREAD

**Issue by mattbriggs** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#8]
In using the docker image, I am able to load the URL, but the token returns:
'Invalid credentials'

I'm using Windows 10 Pro Docker version 18.09.1, build 4c52b90

**Comment by ptwobrussell** [comment]
@mattbriggs - Just wanted to circle back with you. Did you get this figured out? Typically, when you start Jupyter, you'll see some console output with a URL containing a token in it that you can use to login for the first time. (If you just access a URL without the token in it, you won't be able to access the notebook.) Is this what you're running into?

**Comment by mattbriggs** [comment]
@ptwobrussell My issue was that I was loading the container and then getting the URL with the token. However, the notebook wasn't recognizing the token. I fussed with the image for a bit and then got the notebook to accept the token. I don't remember now what I did. Once the notebook loaded, however, the contents of the notebook were empty. My modules however were loaded. So I was able to import the notebook files manually and have been working through the book that way. Thanks for geting back to me, btw.

**Comment by ptwobrussell** [comment]
@mattbriggs - Awesome, it sounds like you are all squared away now? (Apologies for the delayed response.) I'll go ahead and close this out, but please re-open it or file new issues as things come up. I definitely want to make sure everything works for you!
