### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by uzabumuhire** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#9]
I am using Docker on Mac OS Mojave 10.14.13 and "Appendix C - Python & Jupyter Notebook Tips" section "Interact with the Virtual Machine without an SSH Client Using Python" has the following error :

AttributeError                            Traceback (most recent call last)
<ipython-input-18-fb9dfd56281c> in <module>
      2 
      3 # Run a command just as you would in a terminal
----> 4 r = envoy.run('ps aux | grep jupyter') # show processes containing 'jupyter'
      5 
      6 # Print its standard output

/opt/conda/lib/python3.6/site-packages/envoy/core.py in run(command, data, timeout, kill_timeout, env, cwd)
    212         cmd = Command(c)
    213         try:
--> 214             out, err = cmd.run(data, timeout, kill_timeout, env, cwd)
    215             status_code = cmd.returncode
    216         except OSError as e:

/opt/conda/lib/python3.6/site-packages/envoy/core.py in run(self, data, timeout, kill_timeout, env, cwd)
     91         thread.join(timeout)
     92         if self.exc:
---> 93             raise self.exc
     94         if _is_alive(thread) :
     95             _terminate_process(self.process)

/opt/conda/lib/python3.6/site-packages/envoy/core.py in target()
     78                 if sys.version_info[0] >= 3:
     79                     self.out, self.err = self.process.communicate(
---> 80                         input = bytes(self.data, "UTF-8") if self.data else None
     81                     )
     82                 else:

/opt/conda/lib/python3.6/subprocess.py in communicate(self, input, timeout)
    841 
    842             try:
--> 843                 stdout, stderr = self._communicate(input, endtime, timeout)
    844             finally:
    845                 self._communication_started = True

/opt/conda/lib/python3.6/subprocess.py in _communicate(self, input, endtime, orig_timeout)
   1494                 stderr = self._fileobj2output[self.stderr]
   1495 
-> 1496             self._save_input(input)
   1497 
   1498             if self._input:

/opt/conda/lib/python3.6/subprocess.py in _save_input(self, input)
   1570                 if input is not None and (
   1571                     self.encoding or self.errors or self.universal_newlines):
-> 1572                     self._input = self._input.encode(self.stdin.encoding,
   1573                                                      self.stdin.errors)
   1574 

AttributeError: 'bytes' object has no attribute 'encode'

**Comment by mikhailklassen** [comment]
With @ptwobrussell's PR, I think this the issue should be resolved. I'm going to close it for now, but please feel free to open it again if related problems persist.
